# Questions

## Getting started

* install R and RStudio

* install the packages `dplyr`, `lubridate`, `jsonlite`

* load the `lubridate` package

* Read the manual page for `tibble`: (`?tibble`)

* read the package vignette for `lubridate`: (`vignette("lubridate")`)


## Data Types

* Does R make a distinction between `1`, `1.0` and `1 + 0i`?


* for the built-in `rivers` data set, how many are greater than 1000? How many are between 100 and 200?


* run this command: `parse_date_time("2016-02-29", "ymd")`. Can you tell what it does? Is 2016 a leap year? Is 2017? Is 2100?

* Can you figure out how many seconds there are in a day (without multiplying `60*60*24`)?



* can you add logical values? If so, how do they turn into numbers?

* can you multiply boolean values? That is, does something like this make sense `x * (x > 0)` and if so, what does it do?

* Guess the output of this command: `TRUE == 1`, Were you right?

* DeMorgan's law says something about the relationship of operations
  using boolean values. By experimenting, can you verify if "not (A or
  B)" is (not A) or (not B)? You experiment by looking at combinations
  of either `!(TRUE | FALSE)` versus things like (!TRUE) | (!FALSE),
  say. (`|` is not, `|` is "or" and `&` is "and")

* Make `x` and `y` with different lengths, says `x<-c(1,2,3)` and `y<-c(1,2,3,4)`. Can you add the two? Multiply? If so, explain how it seems to work


## Containers

* The built in data sets `rivers`, `state77`, and `mtcars` are what type of container?

- For any vectors, are there names? What is the length? What it the class

- for matrices, are there row names, column names? What is the dimension

- for data frames, are there row names? column names, the dimension

* Load the `MASS` package (a builtin). We consider the `Cars93` data set. It is a data frame.

- what are the variable names?

- What kind of variable is the one counting the number of cylinders?

- how many "cases" are there?

- are the cases labeled with row names or some other way?

- One of the variables is for highway mileage. What is the greatest value? smallest value? (`maximum`, `minimum`), what is the average value? the "middle" values (`mean`, `median`). What is the variability? (`IQR` or `sd` measure this)


* Again with the `Cars93` data set from the `MASS` package...

- for the `Cars93` data set, what is the average horsepower for the cars with highway mileage better than 25? Lower than 15?

- for the `Cars93` data set, what is the largest price difference between minimum and maximum price? Smallest?

- For the `Cars93` data set, what are the top 3 cases for highway mileage per potential passengers? (If a car carries 10 people and gets 20 MPG, then the answer is 2 for that car)

- How many cases in the data set have `USA` as the origin? How many are non-USA?

- Is the heaviest car also the car with the worst gas mileage (HWY)? What about lightest car, is it the best mileage?

- On average do front-wheel cars get better mileage than rear wheel cars, based on this data?

- If we think of cars as rectangles (`Length` and `Width`) having a certain density (let's say area over `Weight`), what cars are most dense here? Least dense?


* A phone list has names, numbers and addresses for many different people. Explain how you might store this in R

* A shopping list has items to buy along with quantities. Explain how you might store this in R

* Recall a reduction takes some summary of an object `x` that has lower dimension. For a vector, this would be, say, a single numeric summary. Are the function `mean`, `sd`, `length` reductions?


* Run this command `out <- hist(rivers)`. If we hadn't saved the output, a graphic would be produced. Instead a list is assigned to `out`. What are the components? Could this list have been a data frame instead? The attribute `class` controls how this item is displayed, what class is this list? Does that mean `out` is not a list? (Use `is.list(out)` to ask.)

* make two small vectors `x<-c(1,2,3)`, `y<-c(4,5,6)`. What is `c(x,y)`? A vector of numbers? A vector of two vectors? If not the latter, how might you make that type of object?


## Working with containers


* Load the `nycflights13` package. (You may need to install it), and we will consider the `flights` data set.

- create a data set of just the `UA` flights. How many are there?
- for the `UA` flights, how many were from `EWR`
- For `UA` flights from `EWR` can you tell which month had the most flights?

* For the `flights` data set

- which plane (tail number) had the longest flight?
- which plane (tail number) flew the most flights? most miles?
- which plane had the most flights in one day?

* For the `flights` data set, 

- what was the busiest airport? busiest airline?
- At `EWR` was the busiest airline the same as at `JFK`.
- Can you find the busiest airline for each airport?

* For the `flights` data set, a histogram of delay times can be generated by `hist(flights$arr_delay)`. Creating histogram by carrier can be of more interest. How might that be done given the tools we've talked about? How might you want that to have been done? (Boxplots can be produced by `boxplot(arr_delay ~ carrier, flights)`.)

## Functions



XXX work on these

* XXX write a function to make a request for ...

* time series plots...

* list possible values for a variable

* percentage closed

* time to close distribution

* In your neighborhood, what is the most common complaint historically? In the past year?




----


